### ISSUE TITLE
Can't catch spotipy.SpotifyException

### ISSUE THREAD

**Issue by Libroru** [spotipy-dev/spotipy#1023]
When using an invalid album name for the query, it will throw an error that can't be caught with a try except:

```python
try:
    results = sp.search(q=album, type="album")
except spotipy.SpotifyException:
    print("Album not found!")
```

```
File "/Users/user/PycharmProjects/ChartsGrabber/main.py", line 141, in main
    add_to_spotify("NewJeans", "2nd EP 'Get Up'")
  File "/Users/user/PycharmProjects/ChartsGrabber/main.py", line 44, in add_to_spotify
    result_album_tracks = sp.album_tracks(result_album_id)
  File "/Users/user/PycharmProjects/ChartsGrabber/venv/lib/python3.9/site-packages/spotipy/client.py", line 474, in album_tracks
    trid = self._get_id("album", album_id)
  File "/Users/user/PycharmProjects/ChartsGrabber/venv/lib/python3.9/site-packages/spotipy/client.py", line 1990, in _get_id
    raise SpotifyException(400, -1, "Unsupported URL / URI.")
spotipy.exceptions.SpotifyException: http status: 400, code:-1 - Unsupported URL / URI., reason: None

```

**Comment by bearsyankees** [comment]
Could you share more of your code? I am having trouble replicating this issue

**Comment by Libroru** [comment]
https://pastebin.com/W2Zb39BW

Here's the source code.
I don't really think that most of it is even a factor in this issue, since I am using a return directly after calling `add_to_spotify()` for debug reasons...

**Comment by dieser-niko** [comment]
So it looks like if you use an invalid album name and the `artist` can't be found in any of the results, the variable `result_album_id` will still be an empty string resulting in an error at `result_album_tracks = sp.album_tracks(result_album_id)` (as the error message suggests)

**Comment by Libroru** [comment]
It seems like I removed the return that comes after the print statement in the except-clause before I uploaded the code!
It does seem to be the issue that you've found, however when I add the return statement to the except-clause, the code is never called and does not exit out of the `add_to_spotify()` function.

**Comment by Libroru** [comment]
So it seems like using try-except only works when I use it inside of main() with the add_to_spotify function. I guess I don't know how python works...
