### ISSUE TITLE
Cannot import spotipy on windows

### ISSUE THREAD

**Issue by 5aumit** [spotipy-dev/spotipy#1029]
I installed spotipy into a virtual environment on my windows machine with this command.
`pip install spotipy`
It installs without any errors. When I run `pip list` within my virtual environment it also shows up as `spotipy  2.23.0`.

If I run `python` in a terminal and import spotipy, it seems to work. 
However, when I import it in a jupyter notebook or a python console in jupyter lab, it does not work saying there's no module named spotipy.

**Environment:**
 - OS == Windows 11
 - Python version == 3.8.0
 - spotipy version == 2.23.0
 - IDE == Jupyter Lab

**Additional context**
Any other packages that I have installed in my virtual environment are imported with no issues. Its only spotipy which does not import. I also tried installing spotipy with various other commands on the internet regarding specifying pip3, python3, -m etc.

I referred to the following issues but there was no resolution. 
- [#254 ]
- [#34 ]

These are rather old as well. The solution proposed was regarding added compatibility with python 3 but that sounds like an outdated problem.

**Comment by rileyl12** [comment]
I have the same issue

**Comment by BMakx** [comment]
Same issue here

**Comment by dieser-niko** [comment]
Just a quick question: are you all using Jupyter, or does this problem also occur in a Python script?

**Comment by dieser-niko** [comment]
Well, since I didn't get a single answer, I'm going to close this issue.
