### ISSUE TITLE
Link for QR Code to Authorize

### ISSUE THREAD

**Issue by jaredcoh** [spotipy-dev/spotipy#1038]
Hello!
I am looking to create a computer program that connects Genius API and Spotify for a user to visualize lyrics. 

I would like to have a QR Code that would take them to the Spotify Log In / Authorize page so they can see their information, including current song title, artist, and Lyrics through Genius.

I have the authorization working on my account using the Spotipy code, but I would like it to be universal, where someone can just scan the QR code on the main screen and it will just connect to their account via Authorization. 

I was wondering if there was a way to get a link that, if made into a QR code and scanned, would take them to the App-Authorization page and immediately connect to my application.

**Comment by CDeLeon94** [comment]
You'd need to use OAuth, and deploy your code to a public facing server, have the QR direct to your application's webpage, which can automatically redirect for authorization (I'd probably recommend a splash screen before going to auth), and then the oauth page can redirect back to your application.

**Comment by dieser-niko** [comment]
You might want to take a look at this example, which uses Flask: https://github.com/spotipy-dev/spotipy/blob/master/examples/app.py

**Comment by jaredcoh** [comment]
Thank you for everyones help. I will look into flask and hopefully i will help resolve my problem!
