### ISSUE TITLE
 User not registered in the Developer Dashboard

### ISSUE THREAD

**Issue by mirzoyevaa** [spotipy-dev/spotipy#1044]
trying to login to another person account using this example https://github.com/spotipy-dev/spotipy/blob/master/examples/app.py, but keep getting this error
<img width="561" alt="Снимок экрана 2023-11-23 в 16 04 15" src="https://github.com/spotipy-dev/spotipy/assets/122978173/fcd40756-d9fd-45e5-80f1-3313e1092ff5">

**Comment by dieser-niko** [comment]
Your application is probably still in development mode. You have to add other accounts. Go to the Developer Dashboard > your application > Settings > User Management and there you can add users.

**Comment by dieser-niko** [comment]
Closing as it appears that your issue has been resolved.
