### ISSUE TITLE
_regex_spotify_url needs update because of region specific path

### ISSUE THREAD

**Issue by Commandcracker** [spotipy-dev/spotipy#1071]
https://github.com/spotipy-dev/spotipy/blob/a14a28e10c1889cce83eec7a7e1ad4b5944a452d/spotipy/client.py#L121C1-L121C173

The URL has some additions in some regions (for me Germany)
`https://open.spotify.com/intl-de/track/2Y0iGXY6m6immVb2ktbseM?si=22cad793e8e248fe`
`https://open.spotify.com/intl-de/artist/0SwO7SWeDHJijQ3XNS7xEE?si=17xfyfNGROyr18by1fh9sw`

The new `intl-de` will make the regx expression not match anything.

Im not a regx pro but this seames to work:

```
^(http[s]?:\/\/)?open.spotify.com\/(?P<type>track|artist|album|playlist|show|episode|user|audiobook)\/(?P<id>[0-9A-Za-z]+)(\?.*)?$
```
⬇️ (added `.*` after `open.spotify.com\/`)
```
^(http[s]?:\/\/)?open.spotify.com\/.*(?P<type>track|artist|album|playlist|show|episode|user|audiobook)\/(?P<id>[0-9A-Za-z]+)(\?.*)?$
```

**Comment by dieser-niko** [comment]
I think it would be better to add something more distinctive:

Added `(intl-\w\w\/)?` instead of `.*`:
```regex
^(http[s]?:\/\/)?open.spotify.com\/(intl-\w\w\/)?(?P<type>track|artist|album|playlist|show|episode|user|audiobook)\/(?P<id>[0-9A-Za-z]+)(\?.*)?$
```
The intl-<countrycode> is still just optional, so this should work with the old format as well. I'll create a pull request sooner or later to implement this.
