### ISSUE TITLE
Format for searching song with artist name and song name

### ISSUE THREAD

**Issue by Coconut9021** [spotipy-dev/spotipy#1077]
I'm trying to search for songs using the artist name and song title it works of sometimes but it will occasionally put a song from the correct artist but different song or even the same song name but different artist I'm currently using this format to search is there a more accurate way to get this info
![Code_0BRI5wYayl](https://github.com/spotipy-dev/spotipy/assets/126723591/79d5a66e-a2f2-4387-8c0e-2ac78f617a38)

**Comment by stephanebruckert** [comment]
```
artist = "artist"
track_name = "song name"
query = 'track:{0} artist:{1}'.format(track_name, artist)
sp.search(query, limit=1, type='track', market=None)
```

**Comment by Coconut9021** [comment]
Thanks works perfectly
