### ISSUE TITLE
Receiving authentication error when using "current_user_playlists"

### ISSUE THREAD

**Issue by schebook** [spotipy-dev/spotipy#1088]
Hi all, 

As the title says, I'm receiving an authentication error when using the current_user_playlists method. I'm able to run the examples in the Spotipy docs - as I believe they don't require user authentication. A cache file is generated when I run the program with a bearer token as well. 

I have the Client ID, Client Secret and Redirect URI set as environment variables. Not too sure where I'm going wrong. I'm not sure if I need to switch authentication methods, apply a certain scope, or something else. I've attempted to feed SpotifyClientCredentials() a scope to read private playlists to no avail. Any ideas? Below is my code:

```python
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import os
import json

#Getting the client ID and client secret after making them environment varibales
client_id = os.environ.get('SPOTIPY_CLIENT_ID')
client_secret = os.environ.get('SPOTIPY_CLIENT_SECRET')

# print(client_id)
# print(client_secret)

#Performing a check to make sure that the environment variables are remembered.
if client_id is None or client_secret is None:
    print("ERROR: Set SPOTIPY_CLIENT_ID and SPOTIPY_CLIENT SECRET environment variables")

#Entering the URI of the playlist
playlist_uri = "spotify:playlist:37i9dQZF1EJzGGGOWOiITB"
spotify = spotipy.Spotify(client_credentials_manager=SpotifyClientCredentials())


# playlists = spotify.user_playlists("schebook")
# print(json.dumps(playlists, indent=4))

test = spotify.current_user_playlists(limit=20)
print(test)
``` 

and this is the error that I'm getting when trying to run:

```javascript
{
  "error": {
    "status": 401,
    "message": "No token provided"
  }
}
```

**Comment by dieser-niko** [comment]
You may want to replace `SpotifyClientCredentials` with `SpotifyOAuth` or the application will not have a user to work with. This also requires the addition of a `SPOTIPY_REDIRECT_URI`, but you won't get far without one either way.

Also, I'm not sure how you got a JSON output. Normally it throws an error. If there are some additions to your script, make sure to include them if related.

**Comment by schebook** [comment]
Thanks @dieser-niko ! Switching over to SpotifyOAuth allowed this to work. I got the JSON output via a link that was provided in the output. The link, when pasted into my browser, provided the JSON output. I think it's just Spotipy's way of creating an easier to read format.

**Comment by schebook** [comment]
Using SpotifyOAuth fixed the issue that I was having. Make sure to have a redirect URI as mentioned by @dieser-niko
