### ISSUE TITLE
Spotipy use youtube to play song?

### ISSUE THREAD

**Issue by Ludo-code** [spotipy-dev/spotipy#1091]
Hello,

Is spotipy using youtube api to play audio?

**Comment by dieser-niko** [comment]
No, not at all. It can't even play music.

Just out of curiosity, where did you pick that up?

**Comment by Ludo-code** [comment]
Oh I'm sorry I have just confused Spotipy with another repo... Too much time to try solving a problem and so at the end opened the ticket at the wrong location...
