### ISSUE TITLE
playlist_reorder_items not working

### ISSUE THREAD

**Issue by lucas992x** [spotipy-dev/spotipy#1099]
**Describe the bug**
`playlist_reorder_items` is not working: code is executed without errors but tracks in playlist are not reordered.

**Your code**
[Minimal working example](https://pastebin.com/feHvi2VS)
Can be tested by inserting ID of any playlist you have permission to edit, just be sure that it contains enough tracks to perform the test (or change indexes). Includes other tools that work: description of playlist is modified and a track is added to it.

**Expected behavior**
`playlist_reorder_items` should reorder playlist but this does not happen

**Output**
There is no output, command seems to be executed (is there something I should do to retrieve more information?)

**Environments:**
- Windows, Python 3.11.2, Spotipy 2.22.1 (installed with `pip`)
- Debian WSL, Python 3.11.2, Spotipy 2.23.0 (installed from repo with `python setup.py install`)
- Arch WSL, Python 3.12.3, Spotipy 2.23.0 (installed from repo with `python setup.py install`)

**Additional context**
It was working some days ago, then it stopped all of a sudden.

**Comment by dieser-niko** [comment]
I was able to replicate the bug in the interactive [Web API Reference](https://developer.spotify.com/documentation/web-api/reference/reorder-or-replace-playlists-tracks) and it seems to do absolutely nothing.

As a workaround, you can use `Spotify.playlist_replace_items`, but the functionality is a bit different. The URIs provided will replace the entire playlist, even though the function only supports up to 100 songs/episodes. However, if you provide URIs that are already in the playlist, it will count as reordered.

**Comment by lucas992x** [comment]
I tried `playlist_replace_items` and it works, thank you for the advice! Unfortunately most of my playlists contain way more than 100 tracks, so I have to wait that Spotify fix the issue :(

**Comment by jwatson-CO-edu** [comment]
I am having the same issue.  The authorization request `spotipy.util.prompt_for_user_token` does not cause any errors.  I get the following response despite having correct permission in my token request.
```json
{
  "error": {
    "status": 401,
    "message": "No token provided"
  }
}
```
An example that was working as of 2 weeks ago can be [found here](https://github.com/jwatson-CO-edu/yt_shuffle_so_good/blob/main/spotify/03_reorder-PL.ipynb).

**Comment by lucas992x** [comment]
Now `playlist_reorder_items` works again, I close the issue
