### ISSUE TITLE
Enhance Spotipy with Language Information for Tracks

### ISSUE THREAD

**Issue by miki-reynolds** [spotipy-dev/spotipy#1102]
**Is your feature request related to a problem? Please describe.**
Currently, there is no support for retrieving language information for tracks in the Spotipy library. This limitation hinders developers from building language-aware music applications and providing language-specific recommendations to users.

**Describe the solution you'd like**
I would like to request the addition of language information for tracks in the Spotipy library. This feature would involve introducing a new attribute or field in the track metadata response that indicates the language of the song. Additionally, implementing a mechanism to automatically detect the language of the lyrics or title of a song would be beneficial. This language information should be accessible through relevant Spotipy methods, such as `spotify.track()` or `spotify.album_tracks()`.

**Describe alternatives you've considered**
An alternative solution could involve developers manually annotating the language of tracks in their applications. However, this approach is not scalable and requires additional effort from developers. Incorporating automatic language detection within Spotipy would streamline the process and improve efficiency for developers.

**Additional context**
Including language information in track metadata aligns with the growing demand for multilingual music applications. This feature would enhance Spotipy's capabilities and make it a more comprehensive tool for developers working with linguistically diverse music libraries. Below is an example of how this feature might be used:

```python
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

spotify = spotipy.Spotify(client_credentials_manager=SpotifyClientCredentials())

# Retrieve track metadata, including language information
track_info = spotify.track('6rqhFgbbKwnb9MLmUQDhG6')
print("Track Name:", track_info['name'])
print("Language:", track_info['language'])
```

Thank you for considering this feature request. If you need any further clarification or have any questions, please let me know!

**Comment by dieser-niko** [comment]
Sorry, but spotipy is just a wrapper. This enhancement would need to be implemented in the Spotify API.
Lyrics are not available through the developer API, so this would be unreachable as well.
