### ISSUE TITLE
How to delete playlists using spotipy

### ISSUE THREAD

**Issue by JackDyre** [spotipy-dev/spotipy#1106]
Which method should I use to delete a playlist that I own? I didn't see any methods in the documentation that directly delete a playlist (though I could have just missed it) and ChatGPT told me to use current_user_unfollow_playlist, but I get an error whenever I use it:

```python
>>> from main import api_request_manager as a
>>> a.sp.current_user_unfollow_playlist("https://open.spotify.com/playlist/1Rqvqd7cI4AoeDn5Ei3mql?si=0e4a6ef55eeb486f")
HTTP Error for DELETE to https://api.spotify.com/v1/playlists/https://open.spotify.com/playlist/1Rqvqd7cI4AoeDn5Ei3mql?si=0e4a6ef55eeb486f/followers with Params: {} returned 404 due to None
Traceback (most recent call last):
  File "C:\Users\riley\Documents\GitHub\spotify-file-storage\cpy_venv\Lib\site-packages\spotipy\client.py", line 271, in _internal_call
    response.raise_for_status()
  File "C:\Users\riley\Documents\GitHub\spotify-file-storage\cpy_venv\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/playlists/https://open.spotify.com/playlist/1Rqvqd7cI4AoeDn5Ei3mql?si=0e4a6ef55eeb486f/followers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\riley\Documents\GitHub\spotify-file-storage\cpy_venv\Lib\site-packages\spotipy\client.py", line 1069, in current_user_unfollow_playlist
    return self._delete(
           ^^^^^^^^^^^^^
  File "C:\Users\riley\Documents\GitHub\spotify-file-storage\cpy_venv\Lib\site-packages\spotipy\client.py", line 333, in _delete
    return self._internal_call("DELETE", url, payload, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\riley\Documents\GitHub\spotify-file-storage\cpy_venv\Lib\site-packages\spotipy\client.py", line 293, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/playlists/https://open.spotify.com/playlist/1Rqvqd7cI4AoeDn5Ei3mql?si=0e4a6ef55eeb486f/followers:
 None, reason: None
```

Am I using the wrong method or am I using the method incorrectly?

**Comment by JackDyre** [comment]
I figured out that you must input a playlist ID rather than a URL

From the [docs](https://spotipy.readthedocs.io/en/2.22.1/#ids-uris-and-urls):
>Spotipy supports a number of different ID types:
>
>Spotify URI - The resource identifier that you can enter, for example, in the Spotify Desktop client’s search box to locate an artist, album, or track. Example: spotify:track:6rqhFgbbKwnb9MLmUQDhG6
>Spotify URL - An HTML link that opens a track, album, app, playlist or other Spotify resource in a Spotify client. Example: http://open.spotify.com/track/6rqhFgbbKwnb9MLmUQDhG6
>Spotify ID - A base-62 number that you can find at the end of the Spotify URI (see above) for an artist, track, album, etc. Example: 6rqhFgbbKwnb9MLmUQDhG6

>**__In general, any Spotipy method that needs an artist, album, track or playlist ID will accept ids in any of the above form__**

Should this method only accept an IDs and not URLS?

**Comment by dieser-niko** [comment]
Yep, I know about this already. This part of the docs is somewhat misleading because normally spotipy converts URLs automatically (with `Spotify._get_id`), but this conversion doesn't happen everywhere. @stephanebruckert is there a reason for that?

**Comment by dieser-niko** [comment]
Oh, sorry, I just realised I didn't read your question properly. Deleting playlists is not directly possible. 

This may sound silly (because it is imo), but [Spotify believes](https://developer.spotify.com/documentation/web-api/concepts/playlists#following-and-unfollowing-a-playlist) that if you decide to delete your playlist, but there are some followers who like it, then the playlist won't actually be deleted, it will just be removed from your library. 

You can try this yourself by creating a playlist, copying the link, deleting the playlist and then trying to access the playlist via the link. You will then have your playlist back.

I don't really know if the playlists will deleted at some point. If you go to the [recover playlists](https://www.spotify.com/de/account/recover-playlists/), Spotify states that they will delete the playlist after 90 days, but I can't confirm nor deny it.

**Comment by JackDyre** [comment]
Would the fix just be as simple as adding `self._get_id("playlist", playlist_id)` inside the f string in the `current_user_unfollow_playlist()` method?

**Comment by stephanebruckert** [comment]
That should do it @JackDyre, would you be up to open a PR for it?

**Comment by JackDyre** [comment]
Sure!

**Comment by JackDyre** [comment]
Is there a reason why `_get_id()` and similar methods are private? I don't understand why they are even methods of `Spotify` in the first place. Being able to convert between IDs and URIs seems like it would be useful to have in a project.
