### ISSUE TITLE
Get Artist's Albums now expects "include_groups" param instead of "album_type"

### ISSUE THREAD

**Issue by NickyReid** [spotipy-dev/spotipy#1107]
**Describe the bug**
Spotify Web API used to accept album_type param when getting artists albums, even though the docs say the name of the param is include_groups. Today they have updated the API to align with the docs, so the [album_type](https://github.com/spotipy-dev/spotipy/blob/028539e08a5d9d14646ff5118ab3bd80c7458c1f/spotipy/client.py#L423) param in artist_albums is no longer working. I have tested locally replacing the param with include_groups and it works. 

```
def artist_albums(self, artist_id, album_type=None, country=None, limit=20, offset=0):
        trid = self._get_id("artist", artist_id)
        return self._get(
            "artists/" + trid + "/albums",
            include_groups=album_type,
            country=country,
            limit=limit,
            offset=offset,
        )
```

This works. 

[Link to issue on Spotify dev community](https://community.spotify.com/t5/Spotify-for-Developers/Get-Artist-s-Albums-no-longer-accepts-quot-album-type-quot/m-p/6074975#M13945)

**Comment by dieser-niko** [comment]
I'll update it right away. It seems that Spotifys Documentation change was at least more than a year ago, according to the wayback machine.
