### ISSUE TITLE
the playlist function stopped working between yesterday and today

### ISSUE THREAD

**Issue by jbdaudet** [spotipy-dev/spotipy#1117]
sp.playlist() was working fine yesterday, and is stuck today: no error message, just no answer.
All the other function I tested are still working fine: sp.album() sp.artist(), etc.
Maybe an evolution of Spotify web API?

**Comment by jbdaudet** [comment]
You are right: I get a 429 error with the retries=0 option. Not sure why though: I'm asking for one playlist only, and the api is answering to any other request, besides playlist. Thanks a lot for the help!

**Comment by dieser-niko** [comment]
How often are you using this endpoint? Maybe caching might be helpful.

**Comment by dieser-niko** [comment]
And btw, you can actually monitor the usage of the API endpoints in the Spotify dashboard.

**Comment by dieser-niko** [comment]
Hi @jbdaudet, just a quick heads up, we have released a new version (2.25.0) that prints a warning when a limit is reached. I'm not sure if you're still using `retries=0`, but if not, this change will warn you when you reach a limit.
