### ISSUE TITLE
API Reference Refers to Deprecated Methods

### ISSUE THREAD

**Issue by bartokay** [spotipy-dev/spotipy#1118]
Example:
https://spotipy.readthedocs.io/en/2.22.1/#spotipy.client.Spotify.artist_albums

```artist_albums(artist_id, album_type=None, country=None, limit=20, offset=0)```

The docs reference ```album_type```, which has been deprecated and replaced with ```include_groups```. This is noted in ```client.py```, but ```include_groups``` is not mentioned in the docs at all. 

This is just one example - I noticed similar inconsistencies with some other methods in ```client.py``` that have DeprecationWarnings. While some updated methods are documented, the deprecated versions should either be marked as deprecated in the docs or removed entirely.

**Comment by dieser-niko** [comment]
Docs weren't updating correctly. We're already working on a solution to prevent this from happening in the future.

**Comment by dieser-niko** [comment]
We have released a new version. The documentation should now also match the code. Here's a new link to the mentioned function: https://spotipy.readthedocs.io/en/2.24.0/#spotipy.client.Spotify.artist_albums

I'm closing the issue now, as I assume this has been resolved. You can of course reopen it if I missed something.
