### ISSUE TITLE
Documentation for version 2.23.0 not available

### ISSUE THREAD

**Issue by dieser-niko** [spotipy-dev/spotipy#1121]
It seems that after #1120 the site https://spotipy.readthedocs.io returns a 404 not found. The previous versions like [2.22.1](https://spotipy.readthedocs.io/en/2.22.1/) are still available.
There's also the commit cc24b4c22fc8d430a66f08ce45be5f0718e12806, but either the build didn't even trigger or there's another problem.

I don't have access to RTD so I can't really identify/fix the problem.

**Comment by stephanebruckert** [comment]
On it!

**Comment by dieser-niko** [comment]
At least it's now redirecting to 22.2.1 again.

**Comment by dieser-niko** [comment]
Soo is is fixed now? Because I'd like to release a new version and the documentation is the only thing which is holding me back.

**Comment by robert-elles** [comment]
In the meantime are the docs still available through a different link somewhere else?

**Comment by dieser-niko** [comment]
Actually, they are available, currently under this link: https://spotipy.readthedocs.io/en/2.23.0/

Not sure what is going on now. It was working just fine yesterday. @stephanebruckert

**Comment by stephanebruckert** [comment]
> Actually, they are available, currently under this link: https://spotipy.readthedocs.io/en/2.23.0/

RTD responded and renamed the URL 👍 

> Not sure what is going on now. It was working just fine yesterday. @stephanebruckert

Looks like I had to set the default branch again. All fixed now!

**Comment by dieser-niko** [comment]
Then closing issue, seems to be resolved!
