### ISSUE TITLE
Current 2.23.0 install from pip doesn't include latest code

### ISSUE THREAD

**Issue by twointum** [spotipy-dev/spotipy#1123]
Hello, I have tried to uninstall/reinstall multiple times. I have examined the fresh client.py file and the artist_albums function doesn't contain the include_groups parameter. It seems to be using the old code. 

Is anyone else seeing this? 

Thanks!

**Comment by dieser-niko** [comment]
This is not a bug. The latest code just hasn't been released yet, but we plan to do so sometime this week.

**Comment by twointum** [comment]
Awesome! I thought I was going crazy! Is there something I'm overlooking that says that the code on the site is not part of the latest release? I am not a super experienced GitHub user.

**Comment by dieser-niko** [comment]
No problem. If you want to see the code for version 2.23.0 for example, you can select the tag 2.23.0 in GitHub.
Here's a direct link: https://github.com/spotipy-dev/spotipy/tree/2.23.0

**Comment by dieser-niko** [comment]
Closing as it appears that your issue has been resolved.
