### ISSUE TITLE
Update Directions and Content of CONTRIBUTING.md

### ISSUE THREAD

**Issue by bennetthamilton** [spotipy-dev/spotipy#1124]
**Is your feature request related to a problem? Please describe.**
- It is not made clear how to fork the project and submit a pull request in the CONTRIBUTING.md
- There are some inconsistencies with the project's documentation [webpage](https://spotipy.readthedocs.io/en/2.23.0_a/#contribute) (the authors/contributors section is not included)

**Describe the solution you'd like**
- Include a step at the beginning that explains to newer programmers how to fork the repository
- Include a step at the end that explains how to submit a pull request
- Include a section at the end that displays the authors/contributors of the project

**Describe alternatives you've considered**
N/A

**Additional context**
[CONTRIBUTING.md](https://github.com/spotipy-dev/spotipy/files/15487178/CONTRIBUTING.md)
[CHANGELOG.md](https://github.com/spotipy-dev/spotipy/files/15487180/CHANGELOG.md)

**Comment by stephanebruckert** [comment]
It is expected that people who were able to find this library already have minimal knowledge of python/github.
