### ISSUE TITLE
Adding a custom date range for users top tracks and top artist

### ISSUE THREAD

**Issue by ablake12** [spotipy-dev/spotipy#1137]
Hi I'm trying to use the current_user_top_tracks and current_user_top_artists methods to get a user's top artists and tracks. However, the only option that's given for date range is short_term, medium_term, and long_term. Could I request for it to allow custom date ranges as parameters? So for example, adding a start date of 01/01/2024 and an end date of 06/30/2024 and the function would return the top artists or top tracks between that time range. Thank you!

**Comment by dieser-niko** [comment]
Spotipy can only use what is available in the Spotify API. As we are not affiliated with Spotify, we are unable to implement this change. However, you could try posting on the Spotify forum.
