### ISSUE TITLE
Any way to play a playlist? Without premium if possible.

### ISSUE THREAD

**Issue by DogeLord081** [spotipy-dev/spotipy#1139]
I'm looking for any ways to play songs in Spotify with this API without premium, and I was hoping that at least playing a playlist doesn't require premium.

**Comment by dieser-niko** [comment]
Sorry, Spotipy can't help you with that. The [documentation](https://developer.spotify.com/documentation/web-api/reference/start-a-users-playback) clearly specifies a premium account as a requirement. There are other ways via the `api-partner.spotify.com` endpoint, but that requires a user token and so much more, that I personally wouldn't recommend spending time on it.
