### ISSUE TITLE
Podcast transcript

### ISSUE THREAD

**Issue by markseery** [spotipy-dev/spotipy#1142]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Podcast Transcript (in text)

**Describe alternatives you've considered**
Getting transcript from audio playback.

**Additional context**
None.

**Comment by dieser-niko** [comment]
Please see the first question in our [FAQ](https://github.com/spotipy-dev/spotipy/blob/master/FAQ.md).
