### ISSUE TITLE
How spotipy have to be setted  for deploying?

### ISSUE THREAD

**Issue by Mau5trakt** [spotipy-dev/spotipy#1145]
Hello im using Spotipy to make something like [last.fm](last.fm) (im running a script every 20 secs to see if all my users are playing music, then register it into a database)
when im in the local enviroment for some reason it ask me to sign up every so often, but now i've deployed and i see the script is trying to open a web browser in the terminal to log into the spotipy aplication. so, how i should work with it?

also i made a custom cache handling that in simple words save the cache token for every user into the database and then when the program that verifies if a user is playing a track ill ask for his tokens creds into the database.

**Comment by dieser-niko** [comment]
There are several ways to approach this problem. I'd say the [app.py](https://github.com/spotipy-dev/spotipy/blob/master/examples/app.py) would be the most appropriate for your application. But if you're deploying frontend and backend separately, I'd recommend something like my [spotipy-fastapi-oauth](https://github.com/dieser-niko/spotipy-fastapi-oauth) example.
