### ISSUE TITLE
Playlist longer than 100 items fails to iterate with sample code

### ISSUE THREAD

**Issue by cbz** [spotipy-dev/spotipy#1155]
The example code under "Show the contents of every playlist owned by a user:" fails when playlists are longer than 100 items.

Expected behaviour would be to print out all contents of each playlist.

In reality an exception is thrown when a playlist longer than a single page of results is encountered:

The following is seen:

{'next': None}
Traceback (most recent call last):
  File "/tmp/sptest.py", line 40, in <module>
    show_tracks(tracks)
  File "/tmp/sptest.py", line 9, in show_tracks
    for i, item in enumerate(tracks['items']):

**Environment:**
 - OS: Ubuntu 20.04.6 LTS
 - Python version 3.12.0
 - spotipy version 2.24.0

**Comment by dieser-niko** [comment]
I'm guessing you mean this example: [user_playlists_contents.py](https://github.com/spotipy-dev/spotipy/blob/master/examples/user_playlists_contents.py).

I ran it and it worked fine. Could you copy the entire error message? And if you have modified your script, please share it.

**Comment by cbz** [comment]
I'm using the second example here with the auth flow listed. 

https://spotipy.readthedocs.io/en/2.11.1/#examples

The text in my original issue is the extent of the error message, and output at the point where a, a playlist longer than 100 items is encountered, and just after the first 100 (0-99) results have been printed out.

**Comment by cbz** [comment]
Looks like the interface changed slightly such that the older code no longer worked, closing issue.
