### ISSUE TITLE
 Running .artist() & .album_tracks() methods are stuck running & won't execute

### ISSUE THREAD

**Issue by danisuba10** [spotipy-dev/spotipy#1157]
**Describe the bug**
After reaching said functions, going a line under with debugger shows nothing, like being stuck in an infinite cycle elsewhere. Going inside, goes into the library's functions, so it gets stuck somewhere there, not in my code.

This happens randomly. Sometimes it works, sometimes not. For some time it works flawlessly, and another time it gets stuck indefinitely. I tried switching Spotify accounts to check if it is a rate limit, but things did not change.

**Your code**
https://github.com/danisuba10/APIDataGenerator/blob/main/Sources/Generator/AlbumGenerator/AlbumMetadataGenerator.py

```
artist_details = self.sp.artist(artist['id'])
It gets stuck on the line above, not reaching images line
images = artist_details.get('images', [])
```

```
songs = self.sp.album_tracks(album_id)['items']
It gets stuck on the line above, not reaching song_list line
song_list = []

```
**Expected behavior**

**Output**
No erros, just getting stuck indefinitely.

**Environment:**
 - OS: [Windows]
 - Python version [e.g. 3.12.3]
 - spotipy version [e.g. 2.24.0]
 - your IDE (if using any) [VSCode]

**Additional context**

**Comment by dieser-niko** [comment]
You have probably hit a request limit. urllib will wait until the limit is gone, but with request limits this can take quite a long time.

If you want to get an error message instead, just do the following:
```python3
sp = spotipy.Spotify(
    retries=0,
    ...
)
```

**Comment by danisuba10** [comment]
Yes, checking with that option, it returns too many 429 responses. Thanks.
