### ISSUE TITLE
current_user_followed_artists() results in http status 400

### ISSUE THREAD

**Issue by fivebanger** [spotipy-dev/spotipy#1169]
**Describe the bug**
Call of `current_user_followed_artists(limit=20, after=None)` first time (i.e. `after` is not known yet) results in http status 400.

`current_user_followed_artists(limit=20, after=None)` results in message
```
Sending GET to https://api.spotify.com/v1/me/following with Params: {'type': 'artist', 'limit': 20, 'after': 0} Headers: {'Authorization': 'Bearer xxx', 'Content-Type': 'application/json'} and Body: None
```
whereas `after` evaluates to `0` and spotipy raises exception 
```
File "/home/martin/.kodi/addons/plugin.audio.hotspot/libs/spotipy/spotipy/client.py", line 1439, in current_user_followed_artists
return self._get(
File "/home/martin/.kodi/addons/plugin.audio.hotspot/libs/spotipy/spotipy/client.py", line 327, in _get
return self._internal_call("GET", url, payload, kwargs)
File "/home/martin/.kodi/addons/plugin.audio.hotspot/libs/spotipy/spotipy/client.py", line 297, in _internal_call
raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 400, code:-1 - https://api.spotify.com/v1/me/following?type=artist&limit=50&after=0:
Invalid base62 id, reason: None
```
**Your code**
Call `current_user_followed_artists(limit=20, after=None)` 

**Environment:**
 - OS: Linux Mint / LibreELEC / Win10
 - spotipy version 2.24.0

**Additional context**
Most likely this behavior was changed by Spotify. According to current Spotify developer site, the first call of `/v1/me/following` has to be called without the `after` parameter:
```
curl --request GET \
  --url 'https://api.spotify.com/v1/me/following?type=artist' \
  --header 'Authorization: Bearer xxx...'
```
Quick fix inside function `current_user_followed_artists()`:

Change 
```
return self._get(
    "me/following", type="artist", limit=limit, after=after
)
```
to 
```
if after:
    return self._get(
        "me/following", type="artist", limit=limit, after=after
    )
else:
    return self._get(
        "me/following", type="artist", limit=limit
    )
```
which results in message
```
Sending GET to https://api.spotify.com/v1/me/following with Params: {'type': 'artist', 'limit': 20} Headers: {'Authorization': 'Bearer xxx', 'Content-Type': 'application/json'} and Body: None
```
not sending the `after` parameter. A properly populated list of followed artists is returned.

**Comment by dieser-niko** [comment]
The function works as expected. However, it expects a string or None, not an integer, which you seem to have passed to the function.
