### ISSUE TITLE
Output an iTunes Readable Playlist File

### ISSUE THREAD

**Issue by J-oden** [spotipy-dev/spotipy#1176]
The "--m3u" command will output a playlist as a .m3u8 file which iTunes cannot read.

**Describe the solution you'd like**
I would like to output an iTunes readable playlist file to easily transfer Spotify playlists to a phone.

**Describe alternatives you've considered**
I've tried to change the config.json file, but I have minimal coding experience.
This is as far as I got:
`"m3u_output": "{title}\t{artists}\t{album}\t{genre}\t{duration}\t{disc-number}\t{disc-count}\t{track-number}\t{tracks-count}\t{year}\t{output-ext}"`
I don't know how to add a header row or output as .txt file (without manually changing the extension).

Thanks for considering.

**Comment by dieser-niko** [comment]
Spotipy doesn't offer such a feature. Are you trying to program this yourself?

**Comment by J-oden** [comment]
> Spotipy doesn't offer such a feature. Are you trying to program this yourself?

I’m asking for a new feature and Yes, meanwhile I am attempting to program/customize it myself.

**Comment by J-oden** [comment]
> Spotipy doesn't offer such a feature. Are you trying to program this yourself?

Also, my apologies. I thought I was on _spotdl’s_github page.

**Comment by dieser-niko** [comment]
Alright then, but I'm going to have to close this issue. Spotipy is a library, not a CLI or similar.
