### ISSUE TITLE
.recommendation_genre_seeds() deprecated

### ISSUE THREAD

**Issue by ryq99** [spotipy-dev/spotipy#1179]
I was trying to run `genres = obj.recommendation_genre_seeds().get('genres')` to get a full list of genres in the Spotify recommender 

I got the 404 error `spotipy.exceptions.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/recommendations/available-genre-seeds: None, reason: None`

Wondering is it fully deprecated from now on and do we have specific deprecation plan for the rest of the APIs?

**Comment by dieser-niko** [comment]
#1172

**Comment by dieser-niko** [comment]
> Wondering is it fully deprecated from now on and do we have specific deprecation plan for the rest of the APIs?

We only know as much as the blog says: https://developer.spotify.com/blog/2024-11-27-changes-to-the-web-api
