### ISSUE TITLE
`total` parameter should refer to all types in `search_markets` method

### ISSUE THREAD

**Issue by stephanebruckert** [spotipy-dev/spotipy#534]
Currently we can stop searching all markets when an `total` results are found. However this only applies to the first search type when multiple types are given: 

    search_markets("abba", type="artist,track", total=10) 

https://github.com/plamere/spotipy/blob/f7fb8757e958ee055cf39764ff7070f9d67b7229/spotipy/client.py#L541

**Comment by quanuw** [comment]
Hello, I'm new to this project and would like to contribute! Can I be assigned to this issue?

**Comment by rngolam** [comment]
Hi @stephanebruckert, I'm currently looking into this issue and just want to clarify the desired behavior.

The `limit` parameter specifies the number of items to be returned for each search type. The code will currently truncate the limit as the item count approaches `total`. But what should happen when multiple types are specified?

For example, if the user enters this query:
```
search_markets("abba", limit=10, type="artist,track", total=25)
```
The code will search the first market for 10 artist items followed by 10 track items, bringing the count to 20. At this point, we want to truncate the limit to 5 prior to searching the next market. But should we still get 5 items for **both** artists and tracks, resulting in a count of 30 items? Or do we just want to get the 5 artists tracks and immediately return the 25 results at this point? (along with an empty items array for tracks or something along those lines?)

Thanks!
