### ISSUE TITLE
python3 how to check which version spotipy is installed? also how to install old version?

### ISSUE THREAD

**Issue by greeneryAO** [spotipy-dev/spotipy#703]
just curious on a mac terminal how can I check which version I have currently installed?

Also I want to stay on it, even though spotipy is moving to spotipy3 I'm happy with spotipy 2, I downloaded a bunch of old versions, how can I manually install the one I'm on if I get a new mac?

thank you.

**Comment by Peter-Schorn** [comment]
Use `pip show spotipy` to determine which version is currently installed. Use `pip install spotipy --upgrade` to upgrade to the latest release. Use `pip install spotipy==2.18.0` to install version 2.18.0. See [here](https://pip.pypa.io/en/stable/cli/pip_install/#requirement-specifiers) for more information.

**Comment by greeneryAO** [comment]
appreciate the help, I'm on 2.16.0 and things are working fine so I don't intend to change it, I downloaded the zip, can I later `do pip install spotipy==2.16.0`, if I don't want to go to pip install 2.18.0 or version 3 later? where should the directory be so it finds it?

**Comment by Peter-Schorn** [comment]
You don't need to manually download any zip files. `pip install spotipy==2.16.0` installs spotipy from the python package index directly into a directory where all your scripts can find it. `pip show spotipy` shows you where spotipy is installed.

**Comment by greeneryAO** [comment]
oh I see, that will be perfect then, I thought I might have to point to directory, I downloaded a few old releases just in case but shouldn't be an issue if the python package index keeps old files, thanks for clarifying.
