### ISSUE TITLE
Local files

### ISSUE THREAD

**Issue by XPr0methiumX** [spotipy-dev/spotipy#714]
how do I get local file song name using spotipy? coz ive noticed that if a playlist has a local file, it doesn't play the songs at all and gives no error, so i wrapped it up to a try except and made it continue the process on an exception and it works but it skips the local files, so how would I go about getting the song name of a local file that's in my playlist using spotipy?

**Comment by stephanebruckert** [comment]
Have a look at https://developer.spotify.com/documentation/general/guides/local-files-spotify-playlists/

You should be able to skip local tracks looking for `is_local`.

Also note that track infos might not be available depending on the quality of the local track metadata:

> The local file information is read by the client software when the file was added to the playlist. Although as much information as possible is taken from the local file, some may be missing so this information is not guaranteed to exist for all local files.

**Comment by Peter-Schorn** [comment]
See also https://support.spotify.com/us/article/local-files/. In particular, you need to make sure the playlist with the local file is downloaded on the Spotify desktop application and any other Spotify client (e.g., the iOS app) where you intend to play the track.

**Comment by XPr0methiumX** [comment]
Oh okay, thanks a lot!

**Comment by dieser-niko** [comment]
Closing as the issue seems to be resolved.
