### ISSUE TITLE
users curently playing podcast info

### ISSUE THREAD

**Issue by acidchu** [spotipy-dev/spotipy#734]
is there a way to get the users curently playing podcast info been trying this one for a few hours just want to know if im missing something

**Comment by jkotowicz1** [comment]
Wow! When I finally gave up after searching in Spotify Developer Guidelines I stumbled on this answer and it works! How do you know about this? Because I haven't seen in anywhere in official documentation.

**Comment by Peter-Schorn** [comment]
Spotify recently updated their documentation and now it includes less detail. This information used to be in the documentation.

**Comment by dieser-niko** [comment]
Closing as the issue seems to be resolved.
