### ISSUE TITLE
Response fields missing from /tracks

### ISSUE THREAD

**Issue by MatejBevec** [spotipy-dev/spotipy#743]
Hi, I have a question about the response from `spotipy.tracks()`.

It seems like the Spotify API was recently updated and now, according to the documentation, the call to `https://api.spotify.com/v1/tracks` should return *artists' genres* and some other info:

![image](https://user-images.githubusercontent.com/40042371/141449369-6ef9a0bf-2cfd-415b-9073-2d406370fc53.png)

However, when using `spotipy.tracks(track_ids)` , these fields are missing:
```
 'artists': [
    {
      'external_urls': {
        'spotify': 'https://open.spotify.com/artist/1bgyxtWjZwA5PQlDsvs9b8'
      },
      'href': 'https://api.spotify.com/v1/artists/1bgyxtWjZwA5PQlDsvs9b8',
      'id': '1bgyxtWjZwA5PQlDsvs9b8',
      'name': 'Sarah Vaughan',
      'type': 'artist',
      'uri': 'spotify:artist:1bgyxtWjZwA5PQlDsvs9b8'
    }
  ],
```

What may be the explanation for this?

**Comment by dieser-niko** [comment]
Hm. Seems to be a bug on Spotify's part. The library doesn't change the response from Spotify, it just parses the JSON. As a workaround just use `sp.artists(artists)`.

By the way, you can use the [Spotify Console](https://developer.spotify.com/console/get-several-tracks/) to test API calls.

**Comment by stephanebruckert** [comment]
Spotify doesn't always have the `genres` for an artist, so it's not returning anything. Nothing wrong here, closing.

**Comment by dieser-niko** [comment]
That's not entirely true. Yes, sometimes the artist itself doesn't add genres, but let's take Ed Sheeran as an example. If you use `sp.artist("6eUKZXaKkcviH0Ku9w2n3V")`, two genres will be displayed. But if you use `sp.track("3rmo8F54jFF8OgYsqTxm5d")` (one of his tracks), then no genres are displayed.

**Comment by stephanebruckert** [comment]
A track can have a different genre than the one specified for its artist?
