### ISSUE TITLE
Fetching "connecting to new output device"

### ISSUE THREAD

**Issue by LuddeLump** [spotipy-dev/spotipy#783]
Hi, im trying to automate my hifisetup with raspberry pi. I would prefer to control everything via the Spotify app, as opposed to also having to use my amp remote. Is it possible to fetch any information when trying to connect to a new output device? If that's possible, it would allow me to make that as an event to turn on my amplifier with a raspberry powered ir controller.

**Comment by dieser-niko** [comment]
Hi there, sorry for the late answer. You could use something like `sp.devices()` to retrieve a list of all devices that are available online. It includes details like `id`, `name`, `type`, `volume`, `is_active`, ...

**Comment by stephanebruckert** [comment]
Solution provided, closing
