### ISSUE TITLE
How to change location of .cache? (Reading or writing)

### ISSUE THREAD

**Issue by clemwo** [spotipy-dev/spotipy#784]
Hi, I wrote a little command line interface that can be used to merge playlists. Code can be found here: 
https://gitlab.com/clemwo/spotify-playlist-merger

I used setuptools for installation and click to make the cli. 

Now when I run the script in the terminal in the folder where it is installed at ``~/.local/share/SpotifyPM`` everything works fine. However if I execute the command from another place such as my home directory I get the followinge message: 
``Couldn't read cache at: .cache``  
The error isn't surprising because apparently spotipy looks for the .cache file in the current working directory (this is just my assumption).  
How can I make spotipy look for the .cache file in another place? I have used [platformdirs](https://pypi.org/project/platformdirs/) to generate a config file in the user data location so it would be nice if that could also be the location where I save the .cache.

Thanks for any help and for the great library!

**Comment by Peter-Schorn** [comment]
You can specify an absolute path for where the authorization information should be stored, as described [here](https://github.com/plamere/spotipy/issues/712#issuecomment-1048360819).

**Comment by dieser-niko** [comment]
Closing as the issue seems to be resolved.
