### ISSUE TITLE
Using util.prompt_for_user_token on a headless machine, can't use open_browser=False?

### ISSUE THREAD

**Issue by kingofsquirrel** [spotipy-dev/spotipy#792]
Okay, so I've recently moved on to a Raspberry Pi although whenever I try to use Spotipy it gets stuck.
I figured out that the problem is that normally, a browser window would open so I can authenticate my program.
I'm now working on a headless machine so it of course doesn't work.
There has been an issue like this before and it was said that there was the variable open_browser added, which is exactly what I'm looking for.
Although with my method of authorisation, I can't use open browser?

The only pieces of code I have are

`token = util.prompt_for_user_token(username=username,scope=scope, client_id=client_id_spotify, client_secret=client_secret_spotify, redirect_uri=redirect_uri)`

and then

`sp = spotipy.Spotify(auth=token)`

The problem is that open_browser can't be used with util, and I have no idea how to get it working.

**Comment by stephanebruckert** [comment]
`spotipy.util.prompt_for_user_token()` is deprecated and it is now recommended to use:

    spotipy.Spotify(auth_manager=SpotifyOAuth(open_browser=False))

See https://github.com/spotipy-dev/spotipy/blob/master/examples/headless.py for an example
