### ISSUE TITLE
Bug in getting values from current_user_playing_track()

### ISSUE THREAD

**Issue by Dimokat** [spotipy-dev/spotipy#801]
When i want to get the key 'name' from the dict, which i get from this method it returns None. It's because there is two keys named 'name', first one is artist name, and the second one is song name, please rename it somehow, it's makes troubles when you want to get some song info.

**Comment by Peter-Schorn** [comment]
The type of the value returned by this method is a nested dictionary. Do you not know how to access nested values in dictionaries?
