### ISSUE TITLE
Suggested improvements to README regarding bug reports

### ISSUE THREAD

**Issue by Spencer-Wise** [spotipy-dev/spotipy#817]
I am taking a class on Open Source Software, and for this class I had to review documentation for an open source project and suggest improvements. I looked at Spotipy's documentation and wrote a report detailing recommendations for ways to improve the visibility and completeness of the README's Bug Report section. This report is attached. Specifically, it suggests:
1. Add a section specifically for bug reports in the README
2. Put the prompts that are found when actually submitting a bug report in the README under this section
3. Add more details to the prompts
4. Better explain navigation to the page where users actually submit bug reports
5. Emphasize the importance of following the prompts.

More details for each section can be found in the attached report.

Each of these recommendations would ideally help users submit higher quality bug reports, saving the devs time and effort in tracking down and fixing bugs.

It's worth noting, while my report focuses on the README, all of these recommendations could be applied to the readthedocs website, as well, as the bug reporting section of the website faces the same perceived issues as the README. 

[report2supplement.pdf](https://github.com/plamere/spotipy/files/8827895/report2supplement.pdf)

**Comment by stephanebruckert** [comment]
More information is already given once you click on "New Issue" https://github.com/spotipy-dev/spotipy/issues/new/choose

https://github.com/spotipy-dev/spotipy/tree/master/.github/ISSUE_TEMPLATE
