### ISSUE TITLE
429 errors are returning an empty set of headers

### ISSUE THREAD

**Issue by lhenslee** [spotipy-dev/spotipy#829]
**Describe the bug**

**Your code**
Share a complete minimal working example.

**Expected behavior**

**Output**
Paste and format errors (with complete stacktrace) or logs. Make sure to remove sensitive information.

**Environment:**
 - OS: [e.g. Windows, Mac]
 - Python version [e.g. 3.7.0]
 - spotipy version [e.g. 2.12.0]
 - your IDE (if using any) [e.g. PyCharm, Jupyter Notebook IDE, Google Colab]

**Additional context**

**Comment by Peter-Schorn** [comment]
Please do not leave the placeholder text in the post. Delete it, if necessary.
