### ISSUE TITLE
oauth2.py using raw_input

### ISSUE THREAD

**Issue by itsa-mee-mario** [spotipy-dev/spotipy#835]
```
Traceback (most recent call last):
  File "/home/spotifywalls/.local/lib/python3.9/site-packages/spotipy/oauth2.py", line 115, in _get_user_input
    return raw_input(prompt)
NameError: name 'raw_input' is not defined
```
Raw input isnt available in python3 and causes an error

 - pythonanywhere
 - Python 3.9
 - spotipy 2.20

**Comment by EstebanVargas10** [comment]
+1 

Python 3.9.6

**Comment by stephanebruckert** [comment]
This is resolved https://github.com/spotipy-dev/spotipy/blob/1e05bdba67f8b7e8fcd4b419176a0048c329b1b7/spotipy/oauth2.py#L107..L110
