### ISSUE TITLE
Missing support for <playlist>:recommended

### ISSUE THREAD

**Issue by wicol** [spotipy-dev/spotipy#881]
Getting this in homeassistant:
```
2022-11-10 09:12:15.187 WARNING (SyncWorker_3) [spotipy.client] Expected id of type playlist but found type 7lHEB3qcunczxs19Saxeom spotify:playlist:7lHEB3qcunczxs19Saxeom:recommended
2022-11-10 09:12:15.243 ERROR (SyncWorker_3) [spotipy.client] HTTP Error for GET to https://api.spotify.com/v1/playlists/recommended with Params: {'fields': None, 'market': None, 'additional_types': 'track'} returned 404 due to Invalid playlist Id
```
I'm guessing it's a new type of type that needs to be supported? :)

**Comment by dieser-niko** [comment]
From where exactly is the `:recommended` parameter coming from? Is there another API call before that?

**Comment by dieser-niko** [comment]
Do you have an endpoint? As far as I know, spotipy does not support anything that is not documented by Spotify themselves. When I try to retrieve the current playback when playing a radio playlist, the context (where a playlist would normally be referenced) is always null. 

As a workaround, simply remove the `:recommended`.

**Comment by stephanebruckert** [comment]
It would be good to link this to an issue posted in https://github.com/home-assistant/core as it's unclear what code is being called.

**Comment by dieser-niko** [comment]
@wicol any updates? The only related issue that I could find was this one, which was marked as stale: https://github.com/home-assistant/core/issues/48258

**Comment by wicol** [comment]
Updates? No, not really. Was it not reproducable for you using my instructions?
I can try it again I suppose, brb.

**Comment by dieser-niko** [comment]
The thing is, I've never seen this :recommended "tag" before. To me it seems like this is coming from home assistant, which I don't have since my home is not very smart. I might set it up on a Raspberry Pi, but as I said, I don't have any smart home devices (like WiFi Speakers) to test it with, so I'm not sure how far I can get.
