### ISSUE TITLE
Is there a way to create playlists with Spotipy?

### ISSUE THREAD

**Issue by xD34THROW** [spotipy-dev/spotipy#883]
Perhaps I am missing it, but I'm looking for a `playlist_create()` method. The [API method](https://developer.spotify.com/documentation/web-api/reference/#/operations/create-playlist) exists for it, but I can't find anything in the documentation.

**Comment by stephanebruckert** [comment]
It is `user_playlist_create` on spotipy https://spotipy.readthedocs.io/en/2.21.0/#spotipy.client.Spotify.user_playlist_create
