### ISSUE TITLE
How to send someone a working authorize url?

### ISSUE THREAD

**Issue by Andrew3212** [spotipy-dev/spotipy#926]
I'm trying to send .get_authorize_url across discord so a friend can authorize. It currently allows them to sign in, but after they do, it says **This site can't be reached** 127.0.0.1 refused to connect.
Then if they call the current song command on the discord bot it returns my song, not theirs.
```
async def csong(ctx):
    c.execute("SELECT sp FROM accounts WHERE id = {I}".format(I=ctx.user.id))     
    uid = c.fetchone()[0]
    auth_manager = spotipy.oauth2.SpotifyOAuth(scope='user-read-currently-playing', show_dialog=True, username=uid)
    await ctx.respond(auth_manager.get_authorize_url())
    token = spotipy.util.prompt_for_user_token(uid, scope='user-read-currently-playing', oauth_manager=auth_manager, show_dialog=True )
    sp = spotipy.Spotify(token)
```

**Comment by stephanebruckert** [comment]
If I remember correctly, it's fine to see `This site can't be reached 127.0.0.1 refused to connect`. All your friend needs to do is copy the URL at that point and send it to you, so that you can enter it in your terminal when you get `Enter the URL you were redirected to`.

**Comment by Andrew3212** [comment]
Ok now I'm calling this `sp_oauth.get_authorize_url()` and then in another function I send the url
`code = ctx.options.URL
 token = sp_oauth.get_access_token(code=code, as_dict=False, check_cache=False)`
But then it says this:
spotipy.oauth2.SpotifyOauthError: error: invalid_grant, error_description: Invalid authorization code

**Comment by Andrew3212** [comment]
Just had to parse it! The bot is fully complete now :D
```
code = ctx.options.URL
code = sp_oauth.parse_response_code(code)
print(code)
token = sp_oauth.get_access_token(code=code, as_dict=False, check_cache=False)
```
