### ISSUE TITLE
Get embed links?

### ISSUE THREAD

**Issue by dsm-72** [spotipy-dev/spotipy#932]
**Is your feature request related to a problem? Please describe.**
Using BeautifulSoup to get data from Spotify is very annoying (even when using selenium) because data (e.g. playlist songs) is dynamically rendered based on intersection observers. So this library is a nice way to get all songs in a given playlist. However, they only have external links, not embedded links. It would be cool to be able, given a playlist or a list of tracks, to get the corresponding embed links.

**Describe the solution you'd like**

```
get_embeded_link(track)
```

**Describe alternatives you've considered**
Selenium + Spotipy to go to the track page and click the corresponding buttons to get the embed link.

**Additional context**
Add any other context or code about the feature request here.

**Comment by dieser-niko** [comment]
I'm not sure if it's Spotipy's job to convert a track ID into an embed link, and so I don't think such a function will be implemented. However, you can create such a function yourself. An embed link is very easy to create:
`https://open.spotify.com/embed/track/<track_id>`. So with that you could write a function like this:
```python3
def get_embed_link(track_id):
    return f"https://open.spotify.com/embed/track/{track_id}"
```
You could also remove things like the `spotify:track:` prefix from the track_id, but that's up to you.

**Comment by stephanebruckert** [comment]
You can definitely construct an embed yourself. Note this would be the responsibility of a front-end app rather than back-end app, so probably out of scope for both spotipy or the Spotify API. For example if using react you could use https://www.npmjs.com/package/react-spotify-embed
