### ISSUE TITLE
Compact python examples into a notebook

### ISSUE THREAD

**Issue by mase-git** [spotipy-dev/spotipy#934]
**Is your feature request related to a problem? Please describe.**
No, it is a feature to organize examples scripts in a more efficient way according to my point of view.

**Describe the solution you'd like**
Actually, examples folder is a list of scripts that test some functions of Spotipy. I think that there is not an actual intuitive 1:1 direct reference between implemented functions and its application. A possible solution is a compact and well-formatted examples snippets into a jupyter notebook. It can also provide an initial index where you can find the a sections descriptions and find easily the function application needed using internal links (anchors in html would be enough).

**Describe alternatives you've considered**
The notebook could also be divided into different files, we can arrange functions according to the type of information we want to retrieve (tracks, artists, profiles...). However, I think that this alternative solution is a bit hard to do, caused by the multiple usages of a single function type (for instance: the[ search function](https://github.com/spotipy-dev/spotipy/blob/262e7a0443ece48ce6825f97ad9a3ed205ceb725/spotipy/client.py#L546) can be used to retrieves a lot of different information).

**Additional context**
We can use an initial[ table of contents ](https://stackoverflow.com/questions/21151450/how-can-i-add-a-table-of-contents-to-a-jupyter-jupyterlab-notebook) for a better navigation over the notebook. So, each example can be directly referred by an internal link.

**Comment by stephanebruckert** [comment]
@mase-git great idea, would you like to open a PR for it?

**Comment by mase-git** [comment]
Yep, I will do. I am working on it!

**Comment by stephanebruckert** [comment]
I was thinking we could even have a separate repository for it in https://github.com/spotipy-dev
It would contain the current examples as well as notebooks. Let me know if you think that would be cleaner.

**Comment by mase-git** [comment]
Yes, I agree. It is much better to do it in a separate repository.

**Comment by stephanebruckert** [comment]
Just created and made you a maintainer of https://github.com/spotipy-dev/spotipy-examples

It will be useful particularly when cleaning up the current repo prior the [v3](https://github.com/spotipy-dev/spotipy/issues/652)
