### ISSUE TITLE
Creating an Account

### ISSUE THREAD

**Issue by unofficialdxnny** [spotipy-dev/spotipy#935]
Hi reader! Is it possible to create a Spotify account with the Spotipy Library?

If yes than how? 

Thanks
Dan

**Comment by dieser-niko** [comment]
No, but I have seen other methods of creating one. You might want to check this out: https://github.com/ALIILAPRO/spotify-account-creator

**Comment by stephanebruckert** [comment]
Bit of FAQ https://github.com/spotipy-dev/spotipy/blob/master/FAQ.md#is-there-a-way-to-get-this-field, this isn't something the Spotify API handles
