### ISSUE TITLE
categories of podcast

### ISSUE THREAD

**Issue by lynabenyahia** [spotipy-dev/spotipy#943]
Hello everyone, 
I am making a project on Python and I use spotipy.
I am looking for the way to have all of the podcast's categories. To give you an idea of what I want to code, here is a part of my code for the moment : 

'results = sp.categories(limit=10)
categories = results['categories']['items']
print("What is you preferate podcast's category ?")
for i, category in enumerate(categories): #fonction "enumerate"
    print(f"{i + 1}. {category['name']}")
category_index = int(input("Enter the number of your choice : "))'

The problem is that this code gives me the categories of music and not of podcast and I don't find anywhere the solution to have podcast categories.

Any idea please ?
Thank you for reading me.

**Comment by stephanebruckert** [comment]
@lynabenyahia what did you find?

**Comment by lynabenyahia** [comment]
I finally realized an interface in which I ask the user to enter the theme of his choice and then I propose him the results by using the search function and by sorting the results according to other criteria that he asked
