### ISSUE TITLE
How to interpret pitch/timbre from audio analysis

### ISSUE THREAD

**Issue by Lauralicja** [spotipy-dev/spotipy#944]
Hey!
I'm using spotipy and its audio_analysis for my project, I wanted to have a look into the music components of it. I can see that under `segments` sections there is a `pitches` and `timbre` section as well, which is amazing. 
However, I am not exactly sure how to interpret those values. I cannot see any sign of explanation of them in the documentation - what is the range of those values? what does it mean when timbre is 80 vs -115 ? Can it even be a negative value? Is there any range for certain notes?
Thanks in advance!

**Comment by stephanebruckert** [comment]
This is not Python related, please ask on https://community.spotify.com/
