### ISSUE TITLE
Writer/Producer Credits available on sp.tracks(uri) call

### ISSUE THREAD

**Issue by Rsalganik1123** [spotipy-dev/spotipy#950]
**Is your feature request related to a problem? Please describe.**
On the spotify API, we can have access to the songwriter and producer credits associated with a large variety of songs. However, this is currently unavailable on Spotipy. 
 
**Describe the solution you'd like**
I would really love for this information to be available in relation to tracks using a call like ```sp.tracks(uri)```. This would enable me to apply interesting innovations in citation graph research to musical "citations". 

**Describe alternatives you've considered**
I have not tried this yet but I imagine the only way to access this info is to scrape the web version of the Spotify API. This will probably be quite difficult. 

**Additional context**
Add any other context or code about the feature request here.

**Comment by stephanebruckert** [comment]
Not available on the API so far https://community.spotify.com/t5/Spotify-for-Developers/Getting-credits-on-a-track/td-p/4950934

See https://github.com/spotipy-dev/spotipy/blob/master/FAQ.md#is-there-a-way-to-get-this-field
