### ISSUE TITLE
Is it possible to get the track or playlist id from a mobile share link (https://spotify.link/)?

### ISSUE THREAD

**Issue by SoHectic** [spotipy-dev/spotipy#951]
I am using Spotipy to get the track and artist names from either a track or playlist link but I am unsure how to get them if provided a share link generated from mobile since it is not the same as if you generate a share link from desktop. I have tried to just strip the characters after the "link/" part of the mobile share link but that doesn't seem to work.

**Comment by stephanebruckert** [comment]
Not python related, question for https://community.spotify.com/

**Comment by stephanebruckert** [comment]
Well you are more asking ["Can the Spotify API do that?"](https://github.com/spotipy-dev/spotipy/blob/master/FAQ.md#is-there-a-way-to-get-this-field). I don't think it does but I recommend making sure about it by asking in the appropriate place.

Anyway one idea for you could be to query that spotify.link and see if it redirects to an open.spotify.com URL which would likely contain an ID. Still, this is not something spotipy can handle for you.
