### ISSUE TITLE
Broken Link to Spoitfy Web API on ReadTheDocs site

### ISSUE THREAD

**Issue by CodeZ89** [spotipy-dev/spotipy#966]
**Describe the bug**
Links on the "ReadTheDocs" page to the Spotify Web API are currently sending users to a "404: Page not found" error. It appears that the path to the page has changed and is now through their documentation page. 

**Your code**
Link to webpage: https://developer.spotify.com/documentation/web-api

**Expected behavior**
Navigate to the Web API documentation page. 

**Output**
Current - 404: Page not found

**Environment:**
Mac

<img width="1376" alt="Screenshot 2023-04-21 at 9 18 34 AM" src="https://user-images.githubusercontent.com/74162569/233645939-7661ccb3-eed8-48ba-ad3e-e3164ee6ac1c.png">

<img width="1344" alt="Screenshot 2023-04-21 at 9 19 08 AM" src="https://user-images.githubusercontent.com/74162569/233646070-2ac66a0d-1418-4157-bc8e-cbc3fa5a18af.png">

**Comment by adhil0** [comment]
It looks like Spotify is automatically redirecting [https://developer.spotify.com/web-api](https://developer.spotify.com/web-api) to [https://developer.spotify.com/documentation/web-api](https://developer.spotify.com/documentation/web-api), not sure if this still needs to be addressed

**Comment by stephanebruckert** [comment]
we can update it, but no urgency
