### ISSUE TITLE
Spotipy maintenance ?

### ISSUE THREAD

**Issue by zereftyzzz** [spotipy-dev/spotipy#984]
my friend and I were making a project using spotipy yesterday the code still ran fine yesterday however, today I've tried using my laptop and 2 of my friend's laptops to run the programm nothing appears empty we have been waiting for a long time the terminal is still empty, is there any interference or maintenance on spotipy ?

**Comment by stefanondisponibile** [comment]
hey @zereftyzzz, `spotipy`'s just a library. If anything, that would be Spotify's own servers.

If you checked and you feel something isn't working with the library, you may want to open a different issue providing some context.
