### ISSUE TITLE
Detect played-flag/status of a podcast episode

### ISSUE THREAD

**Issue by jokolo89** [spotipy-dev/spotipy#997]
Hi there,

does anyone know how to detect the played (or finished) -flag/status of a podcast episode via spotipy?

![image](https://github.com/spotipy-dev/spotipy/assets/114160860/04d6d31a-8929-480d-8897-772cc390e998)

Workaround such as [episode duration - elapsed time] won't work because API doesn't have the info about elapsed time (only duration).

Thanks in advance.

**Comment by dieser-niko** [comment]
Correct me if I'm wrong, but isn't the `resume_point` in [Get Episode](https://developer.spotify.com/documentation/web-api/reference/get-an-episode) what you're looking for?

If you're already using that, check your scopes.

**Comment by dieser-niko** [comment]
Closing as it appears that your issue has been resolved.
